name:  githubsecrets
on:
  push:
    branches:
    - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Use My Secret
        run: |
          echo ${{ secrets.MY_SECRET_KEY }}
