name:  githubsecrets
on:
  push:
    branches:
    - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Use My Secret
        run: |
          echo ${{ secrets.MY_SECRET_KEY }}
  my_job1:
    runs-on: ubuntu-latest
    environment: Test
    needs: my_job
    steps:
      - name: Use Client Secret
        run: |
          echo ${{ secrets.CLIENT_SECRET }}
